'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { getSupabaseBrowserClient } from '@/lib/supabase';

export default function CertificateAdmin({ registration, images, sizes, certificates }: any) {
  const supabase = useMemo(() => getSupabaseBrowserClient(), []);
  const [open, setOpen] = useState(false); const [serial, setSerial] = useState(''); const [serials, setSerials] = useState<any[]>([]); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const imageId = registration.gallery_image_id || '';
  useEffect(() => { if (open && imageId) supabase.from('photo_serial_numbers').select('serial_number,used_at').eq('image_id', imageId).order('serial_number').then(({data}: {data: any[] | null})=>setSerials(data||[])); }, [open, imageId, supabase]);
  async function createCertificate(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setMessage(''); const f = new FormData(e.currentTarget); const selectedSize = sizes.find((s:any)=>s.id===f.get('size_id')); const { data, error } = await supabase.rpc('admin_create_print_certificate', { p_registration_id: registration.id, p_image_id: imageId, p_size_id: f.get('size_id'), p_serial_number: f.get('serial_number'), p_print_number: Number(f.get('print_number')), p_edition_total: selectedSize?.edition_size, p_order_number: f.get('order_number'), p_location: f.get('location'), p_capture_year: Number(f.get('capture_year')), p_technical_information: f.get('technical_information'), p_image_history: f.get('image_history') }); setBusy(false); if (error) return setMessage(error.message); setMessage('Certificate created.'); setOpen(false); window.location.reload(); }
  async function addSerial(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); const { error } = await supabase.rpc('admin_add_photo_serial', { p_image_id: imageId, p_serial_number: serial }); setBusy(false); setMessage(error ? error.message : 'Serial added.'); if (!error) setSerial(''); }
  return <div><button type="button" onClick={()=>setOpen(!open)} style={{padding:'8px 12px',cursor:'pointer'}}>{open?'Close':'Create certificate'}</button>{certificates?.map((c:any)=><div key={c.id} style={{marginTop:6}}><Link href={`/admin/dashboard/registrations/certificates/${c.id}`} target="_blank" style={{color:'#9fd'}}>Certificate {c.print_number}/{c.edition_total} · {c.status}</Link></div>)}{open&&<div style={{background:'#222',padding:16,marginTop:10,minWidth:360}}><form onSubmit={addSerial}><label>Six-digit serial number<input value={serial} onChange={e=>setSerial(e.target.value)} pattern="[0-9]{6}" required style={{display:'block',width:'100%',margin:'4px 0 8px'}} /></label><button disabled={busy}>Add serial</button></form><hr/><form onSubmit={createCertificate}><label>Serial number<select name="serial_number" required style={{display:'block',width:'100%',margin:'4px 0 8px'}}><option value="">Select</option>{serials.filter(s=>!s.used_at).map(s=><option key={s.serial_number} value={s.serial_number}>{s.serial_number}</option>)}</select></label><label>Print size<select name="size_id" required style={{display:'block',width:'100%',margin:'4px 0 8px'}}>{sizes.map((s:any)=><option key={s.id} value={s.id}>{s.name} ({s.edition_size} edition)</option>)}</select></label><label>Print number (1…edition)<input name="print_number" type="number" min="1" required style={{display:'block',width:'100%',margin:'4px 0 8px'}} /></label>{[['order_number','Order number'],['location','Location'],['capture_year','Year photo taken']].map(([n,l])=><label key={n}>{l}<input name={n} required style={{display:'block',width:'100%',margin:'4px 0 8px'}} /></label>)}{[['technical_information','Technical information'],['image_history','Image history']].map(([n,l])=><label key={n}>{l}<textarea name={n} required style={{display:'block',width:'100%',margin:'4px 0 8px'}} /></label>)}<button disabled={busy} type="submit">Create and reserve certificate</button></form>{message&&<p>{message}</p>}</div>}</div>;
}
