'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { getSupabaseBrowserClient } from '@/lib/supabase';
import styles from '../AdminShell.module.css';

export default function CertificateAdmin({ registration, sizes, certificates, standalone = false }: any) {
  const supabase = useMemo(() => getSupabaseBrowserClient(), []);
  const [open, setOpen] = useState(standalone); const [serial, setSerial] = useState(''); const [serials, setSerials] = useState<any[]>([]); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const imageId = registration.gallery_image_id || '';
  useEffect(() => { if (open && imageId) supabase.from('photo_serial_numbers').select('serial_number,used_at').eq('image_id', imageId).order('serial_number').then(({ data }: { data: any[] | null }) => setSerials(data || [])); }, [open, imageId, supabase]);
  async function addSerial(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setMessage(''); const { error } = await supabase.rpc('admin_add_photo_serial', { p_image_id: imageId, p_serial_number: serial }); setBusy(false); setMessage(error ? error.message : 'Serial added.'); if (!error) { setSerial(''); const { data } = await supabase.from('photo_serial_numbers').select('serial_number,used_at').eq('image_id', imageId).order('serial_number'); setSerials(data || []); } }
  async function createCertificate(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setMessage(''); const f = new FormData(e.currentTarget); const selectedSize = sizes.find((s: any) => s.id === f.get('size_id')); const { error } = await supabase.rpc('admin_create_print_certificate', { p_registration_id: registration.id, p_image_id: imageId, p_size_id: f.get('size_id'), p_serial_number: f.get('serial_number'), p_print_number: Number(f.get('print_number')), p_edition_total: selectedSize?.edition_size, p_order_number: f.get('order_number'), p_location: f.get('location'), p_capture_year: Number(f.get('capture_year')), p_technical_information: f.get('technical_information'), p_image_history: f.get('image_history') }); setBusy(false); if (error) return setMessage(error.message); window.location.reload(); }
  return <div>{!standalone && <button type="button" className={styles.primaryButton} onClick={() => setOpen(!open)}>{open ? 'Close' : 'Create certificate'}</button>}{!standalone && certificates?.map((c: any) => <div key={c.id} style={{ marginTop: 10 }}><Link href={`/admin/dashboard/registrations/certificates/${c.id}`} target="_blank">Certificate {c.print_number}/{c.edition_total} · {c.status}</Link></div>)}{(open || standalone) && <div className={styles.editorGrid} style={{ marginTop: 24 }}><div className={styles.panel}><h2 className={styles.panelTitle}>Certificate details</h2><form onSubmit={addSerial}><label className={styles.field}><span className={styles.fieldLabel}>Add six-digit photograph serial number</span><input className={styles.input} value={serial} onChange={e => setSerial(e.target.value)} pattern="[0-9]{6}" required /></label><button disabled={busy} className={styles.ghostButton}>Add serial</button></form><form onSubmit={createCertificate}><label className={styles.field}><span className={styles.fieldLabel}>Available serial number</span><select className={styles.select} name="serial_number" required><option value="">Select a serial</option>{serials.filter(s => !s.used_at).map(s => <option key={s.serial_number} value={s.serial_number}>{s.serial_number}</option>)}</select></label><label className={styles.field}><span className={styles.fieldLabel}>Print size</span><select className={styles.select} name="size_id" required>{sizes.map((s: any) => <option key={s.id} value={s.id}>{s.name} · edition of {s.edition_size}</option>)}</select></label><div className={styles.row2}><label className={styles.field}><span className={styles.fieldLabel}>Print number</span><input className={styles.input} name="print_number" type="number" min="1" required /></label><label className={styles.field}><span className={styles.fieldLabel}>Year photo taken</span><input className={styles.input} name="capture_year" type="number" min="1800" max="2100" required /></label></div>{([['order_number', 'Order number'], ['location', 'Location']] as const).map(([name, label]) => <label className={styles.field} key={name}><span className={styles.fieldLabel}>{label}</span><input className={styles.input} name={name} required /></label>)}{([['technical_information', 'Technical information'], ['image_history', 'History of the image']] as const).map(([name, label]) => <label className={styles.field} key={name}><span className={styles.fieldLabel}>{label}</span><textarea className={styles.textarea} name={name} required /></label>)}<div className={styles.editorActions}><button disabled={busy} type="submit" className={styles.primaryButton}>Create and reserve certificate</button>{message && <span role="status" className={styles.fieldHint}>{message}</span>}</div></form></div></div>}</div>;
}
