import Link from 'next/link';
import styles from './Outreach.module.css';
const contacts = [
  { name: 'Anna Lindström', company: 'Atelier Nord', email: 'anna@ateliernord.se', location: 'Stockholm, SE', status: 'approved', outreach: 'delivered' },
  { name: 'Mikael Berg', company: 'Studio Berg', email: 'hello@studioberg.dk', location: 'Copenhagen, DK', status: 'needs review', outreach: 'not contacted' },
  { name: 'Sofia Ek', company: 'Ek Interiors', email: 'sofia@ekinteriors.se', location: 'Malmö, SE', status: 'approved', outreach: 'opened' },
];
export default function OutreachPage() { return <div className={styles.page}><header className={styles.header}><div><p className={styles.eyebrow}>Private outreach desk · local mode</p><h1 className={styles.title}>Interior designer outreach</h1><p className={styles.subtitle}>A considered place to review contacts, prepare personal invitations, and keep every conversation accountable.</p></div><div className={styles.actions}><Link className={styles.buttonSecondary} href="/admin/outreach/import">Import workbook</Link><Link className={styles.button} href="/admin/outreach/campaigns/new">New campaign</Link></div></header><section className={styles.grid}>{[['Contacts','248','12 need review'],['Approved audience','196','79% of contacts'],['In flight','1','Scandinavia · draft'],['Replies','14','5 follow-ups due']].map(([label,value,meta])=><article className={styles.stat} key={label}><div className={styles.statLabel}>{label}</div><div className={styles.statValue}>{value}</div><div className={styles.statMeta}>{meta}</div></article>)}</section><section className={styles.panel}><div className={styles.panelHead}><h2 className={styles.panelTitle}>Contacts needing attention</h2><Link className={styles.link} href="/admin/outreach/contacts">View all contacts →</Link></div><table className={styles.table}><thead><tr><th>Contact</th><th>Location</th><th>Approval</th><th>Outreach</th></tr></thead><tbody>{contacts.map((contact)=><tr key={contact.email}><td><strong>{contact.name}</strong><br/><span>{contact.company} · {contact.email}</span></td><td>{contact.location}</td><td><span className={`${styles.chip} ${contact.status === 'approved' ? styles.chipGood : styles.chipWarn}`}>{contact.status}</span></td><td><span className={`${styles.chip} ${contact.outreach === 'opened' ? styles.chipGood : ''}`}>{contact.outreach}</span></td></tr>)}</tbody></table></section></div>; }

